spring.application.name=CrudApi

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=validate

jwt.secret=77yh6Us54Ypy3UL/ntknr5s0yVzeJctoWMcOp7ZFJAU=